# Generated by Django 4.2.2 on 2025-08-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="электронный адрес"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ф.И.О.")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["email", "name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=100, verbose_name="тема письма"),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="тело письма"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "last_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status_mailing",
                    models.CharField(
                        choices=[
                            ("start", "Создана"),
                            ("run", "Запущена"),
                            ("end", "Завершена"),
                        ],
                        default="Создана",
                        max_length=10,
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="mailing",
                        to="emailservisapp.client",
                        verbose_name="получатели",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing",
                        to="emailservisapp.message",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status_mailing", "message"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status_attempt",
                    models.CharField(
                        blank=True,
                        choices=[("sucsess", "Успех"), ("unsucsess", "Провал")],
                        max_length=10,
                        null=True,
                        verbose_name="статус попытки",
                    ),
                ),
                (
                    "server_answer",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempt",
                        to="emailservisapp.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["created_at", "status_attempt"],
            },
        ),
    ]
