# Generated by Django 4.2.2 on 2025-08-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emailservisapp", "0003_alter_client_options_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["email", "name"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status_mailing", "message"],
                "permissions": [
                    ("can_end_mailing", "Can end mailing"),
                    ("can_block_user", "Can block user"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
