# Generated by Django 4.2.2 on 2025-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservisapp', '0004_alter_client_options_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='owner_is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Флаг активности владельца'),
        ),
    ]
