# Generated by Django 4.2.2 on 2025-08-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emailservisapp", "0007_alter_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status_mailing", "message"],
                "permissions": [("can_end_mailing", "Can end mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="owner_is_active",
        ),
    ]
